apiVersion: v2
name: unsubscribe
description: A Helm chart for the MOSIP Collab Email Unsubscription page
type: application
version: 0.0.1-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - unsubscribe
  - collab
  - landing-page
maintainers:
  - email: info@mosip.io
    name: MOSIP